### ISSUE TITLE
Cannot Run

### ISSUE THREAD

**Issue by Ethan-Varghese3** [CSAllenISDClassroom/sudokuserver-runtime-terror-1#14]
When trying to do command git pull and then using the commands build and then run there were errors in the code. Then with the help of some classmates I was told to clone he directory again and then used vapor build. This was the following issue and error that appeared: 
![Issue No 3](https://user-images.githubusercontent.com/70398110/138291392-6810749d-c79b-4684-8189-420fd3ae6f9d.PNG)

As a result, we cannot run the API.

**Comment by akshatdotcom** [comment]
You have to use dynamic libraries to run the code. Then, this should not happen. All you have to do is use `build` and `run` instead of `vapor build` and `vapor run` on the shell.
