### ISSUE TITLE
Board JSON doesn't include a value for blank cells

### ISSUE THREAD

**Issue by shariq-h** [CSAllenISDClassroom/sudokuserver-runtime-terror-1#19]
When decoding the JSON, the unfinished cells or cells with no value don't have value in the JSON, which causes issues when trying to decode the value structure for an integer. Is it possible for API to output a 0 instead so that the value can be decoded for an integer value?

**Comment by akshatdotcom** [comment]
Hi, thank you for creating this issue. When a cell does not have a value, "null" or "nil" better fits than 0, so we'll continue to keep it like this. When you access the JSON data of an empty cell, the value key should return null and you can use that.

**Comment by shariq-h** [comment]
I agree that null would be a better replacement, however, the issue is that when the JSON is retrieved, if the value is null, it leaves out the entire bracket, like so.

{"board":
[{"cells":
[{"value":8,"position":{"boxIndex":0,"cellIndex":0}},
{"value":6,"position":{"boxIndex":0,"cellIndex":1}},
{"value":3,"position":{"cellIndex":2,"boxIndex":0}},
**{"position":{"cellIndex":3,"boxIndex":0}},
{"position":{"boxIndex":0,"cellIndex":4}},**
{"value":5,"position":{"cellIndex":5,"boxIndex":0}},
**{"position":{"cellIndex":6,"boxIndex":0}},**
{"value":4,"position":{"cellIndex":7,"boxIndex":0}},
**{"position":{"cellIndex":8,"boxIndex":0}}]},**

**Comment by akshatdotcom** [comment]
Yes, I believe that's the intended functionality. So when you retrieve the "value" key of the cells you bolded, it should return null (aka nil). Is that correct?

**Comment by shariq-h** [comment]
No, it's not finding a value key

**Comment by akshatdotcom** [comment]
Hmm... Could you please elaborate on your error? Providing an image may be useful too :)

**Comment by akshatdotcom** [comment]
I asked the teacher and the omission of the value key is a valid indication of nullness.
