### ISSUE TITLE
Issue No. 2

### ISSUE THREAD

**Issue by Ethan-Varghese3** [CSAllenISDClassroom/sudokuserver-runtime-terror-1#7]
When running the code and using the sudoku server I was getting a board printed in the shell. However this should not be happening and in the sudoku server or W3911, I am getting a hexadecimal string that is: D24F11BE-A1AE-4613-BB3F-00A9C0DA7295. This is a problem because this does not follow the format that is given in W3911 which is something like: 728134. Below is the response I am getting from the shell.
![Issue No 2](https://user-images.githubusercontent.com/70398110/137744405-ee714602-572d-4130-8d27-3ab965e7d000.PNG)

**Comment by akshatdotcom** [comment]
This issue is essentially a replica of #6. Please see that for more details.
